作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [39]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [37]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
eng_avg = np.nanmean(english_score)
eng_max = np.nanmax(english_score)
eng_min = np.nanmin(english_score)
eng_std = np.nanstd(english_score)
print('eng_avg:'+str(eng_avg),
      ',eng_max:'+str(eng_max),
      ',eng_min:'+str(eng_min),
      ',eng_std:'+str(eng_std))

mat_avg = np.nanmean(math_score)
mat_max = np.nanmax(math_score)
mat_min = np.nanmin(math_score)
mat_std = np.nanstd(math_score)
print('mat_avg:'+str(mat_avg),
      ',mat_max:'+str(mat_max),
      ',mat_min:'+str(mat_min),
      ',mat_std:'+str(mat_std))

chi_avg = np.nanmean(chinese_score)
chi_max = np.nanmax(chinese_score)
chi_min = np.nanmin(chinese_score)
chi_std = np.nanstd(chinese_score)
print('chi_avg:'+str(chi_avg),
      ',chi_max:'+str(chi_max),
      ',chi_min:'+str(chi_min),
      ',chi_std:'+str(chi_std))

eng_avg:67.16666666666667 ,eng_max:89 ,eng_min:48 ,eng_std:13.433995020924426
mat_avg:55.0 ,mat_max:55 ,mat_min:55 ,mat_std:0.0
chi_avg:75.33333333333333 ,chi_max:90 ,chi_min:65 ,chi_std:8.825468196582484


In [45]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score_new = np.array([60,85,60,68,55,60])

mat_avg_new = np.nanmean(math_score_new)
mat_max_new = np.nanmax(math_score_new)
mat_min_new = np.nanmin(math_score_new)
mat_std_new = np.nanstd(math_score_new)
print('mat_avg_new:'+str(mat_avg_new),
      ',mat_max_new:'+str(mat_max_new),
      ',mat_min_new:'+str(mat_min_new),
      ',mat_std_new:'+str(mat_std_new))

mat_avg_new:64.66666666666667 ,mat_max_new:85 ,mat_min_new:55 ,mat_std_new:9.860132971832694


In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [52]:
rel = [english_score,math_score_new,chinese_score]
rel

[array([55, 89, 76, 65, 48, 70]),
 array([60, 85, 60, 68, 55, 60]),
 array([65, 90, 82, 72, 66, 77])]

In [53]:
np.corrcoef(rel) #ans:math

array([[1.        , 0.7855563 , 0.97792828],
       [0.7855563 , 1.        , 0.74056803],
       [0.97792828, 0.74056803, 1.        ]])